Description: creates backup vault, and service role for AWS Backup

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleName:
    Type: String
    Description: cross account role name
    Default: service-catalog-platform-exec
  TrustedAccount:
    Type: String
    Description: idp hub account id

Resources:
  IdpRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": !Sub "arn:aws:iam::${TrustedAccount}:root"
                  },
                  "Action": "sts:AssumeRole"
              }
          ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:PassRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:ListRoles
              - iam:DeleteRole
              - iam:DeleteRolePolicy
              - iam:TagRole
              Resource: "*"
            - Effect: Allow
              Action:
              - s3:GetBucketVersioning
              - s3:GetObject
              - s3:GetObject*
              - s3:GetEncryptionConfiguration
              - s3:list*
              Resource: "*"
            - Effect: Allow
              Action:
              - cloudformation:*
              - sqs:*
              - ssm:*
              - lambda:*
              - ecr:*
              Resource: "*"
