Description: creates backup vault, and service role for AWS Backup

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  RoleName:
    Type: String
    Description: cross account role name
    Default: service-catalog-platform-exec
  TrustedAccount:
    Type: String
    Description: idp hub account id

Resources:
  IdpRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                    "AWS": !Sub "arn:aws:iam::${TrustedAccount}:root"
                  },
                  "Action": "sts:AssumeRole"
              }
          ]
      }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSServiceCatalogAdminFullAccess
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - "iam:ListRoles"
              - "cloudformation:*"
              - "sqs:*"
              - "ssm:*"
              Resource: "*"
            - Effect: Allow
              Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:PutRolePolicy
              - iam:PassRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              Resource: "*"
            - Effect: Allow
              Action:
              - iam:DeleteRole
              - iam:DeleteRolePolicy
              Resource: "*"
            - Effect: Allow
              Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetBucketVersioning
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTorrent
              - s3:GetEncryptionConfiguration
              - s3:GetObjectVersion
              - s3:GetObjectVersionAttributes
              - s3:GetObjectRetention
              - s3:GetObjectTagging
              - s3:GetObjectAttributes
              - s3:GetObjectVersionTagging
              - s3:GetObjectTorrent
              - s3:GetObjectVersionForReplication
              - s3:GetObjectLegalHold
              - s3:list*
              Resource: "*"
            - Effect: Allow
              Action:
              - lambda:CreateFunction
              - lambda:TagResource
              - lambda:ListVersionsByFunction
              - lambda:GetLayerVersion
              - lambda:GetFunctionConfiguration
              - lambda:RemoveLayerVersionPermission
              - lambda:UntagResource
              - lambda:ListTags
              - lambda:DeleteLayerVersion
              - lambda:PutFunctionEventInvokeConfig
              - lambda:DeleteFunctionEventInvokeConfig
              - lambda:DeleteFunction
              - lambda:UpdateFunctionEventInvokeConfig
              - lambda:UpdateEventSourceMapping
              - lambda:GetFunction
              - lambda:UpdateFunctionConfiguration
              - lambda:AddLayerVersionPermission
              - lambda:UpdateAlias
              - lambda:UpdateFunctionCode
              - lambda:AddPermission
              - lambda:GetFunctionEventInvokeConfig
              - lambda:DeleteAlias
              - lambda:PublishVersion
              - lambda:DeleteEventSourceMapping
              - lambda:RemovePermission
              - lambda:CreateAlias
              Resource:
              - !Sub arn:aws:lambda:*:${AWS::AccountId}:function:*
              - !Sub arn:aws:lambda:*:${AWS::AccountId}:event-source-mapping:*
              - !Sub arn:aws:lambda:*:${AWS::AccountId}:layer:*:*
            - Effect: Allow
              Action: lambda:PublishLayerVersion
              Resource: !Sub arn:aws:lambda:*:${AWS::AccountId}:layer:*
            - Effect: Allow
              Action:
              - lambda:ListFunctions
              - lambda:ListLayerVersions
              - lambda:ListLayers
              - lambda:CreateEventSourceMapping
              Resource: "*"
            - Effect: Allow
              Action:
              - iam:TagRole
              Resource: "*"
