FROM public.ecr.aws/lambda/python:3.9

# ARG ARG_CDK_APP_S3_BUCKET
# ARG ARG_CDK_APP_S3_PREFIX

# Install the function's dependencies using file requirements.txt
# from your project folder.
RUN yum update -y
RUN yum install -y curl
RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash -


RUN yum install -y nodejs

RUN npm install -g aws-cdk

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY src/index.py ${LAMBDA_TASK_ROOT}

# ENV CDK_APP_S3_BUCKET=$ARG_CDK_APP_S3_BUCKET
# ENV CDK_APP_S3_PREFIX=$ARG_CDK_APP_S3_PREFIX

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ]
