FROM public.ecr.aws/lambda/python:3.12

# ARG ARG_CDK_APP_S3_BUCKET
# ARG ARG_CDK_APP_S3_PREFIX

RUN set -ex \
    && dnf install -y nodejs \
    && npm --version \
    && npm update -g
RUN npm install -g aws-cdk

# Install the function's dependencies using file requirements.txt
# from your project folder.
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN  pip3 install -r requirements.txt

# Copy function code
COPY src/index.py ${LAMBDA_TASK_ROOT}

# ENV CDK_APP_S3_BUCKET=$ARG_CDK_APP_S3_BUCKET
# ENV CDK_APP_S3_PREFIX=$ARG_CDK_APP_S3_PREFIX

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "index.handler" ]
